#define KW_AND 		1
#define KW_OR 		2
#define KW_NOT 		3
#define KW_EQUAL 	4
#define KW_LESS 	5
#define KW_NIL 		6
#define KW_LIST 	7
#define KW_APPEND	8
#define KW_CONCAT 	9
#define KW_SET		10
#define KW_DEFFUN	11
#define KW_FOR 		12
#define KW_IF		13
#define KW_EXIT		14
#define KW_LOAD		15
#define KW_DISP		16
#define KW_TRUE		17
#define KW_FALSE	18
#define IDENTIFIER	19
#define VALUE		20
#define OP_OP      	21   
#define OP_CP		22
#define OP_PLUS		23
#define OP_MINUS	24
#define OP_MULT 	25
#define OP_DIV		26
#define OP_DBLMULT	27
#define OP_COMMA	28
#define OP_OC 		29
#define OP_CC 		30
#define COMMENT		31

